### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by CmdLnInt** [stephdl/smeserver-dhcp-dns#1]
When I do

`yum --enablerepo=stephdl install smeserver-dhcp-dns`

I get 

`Error getting repository data for stephdl, repository not found`

How can I fix this or how can I do a manual install?

**Comment by stephdl** [comment]
follow up http://wiki.contribs.org/Dhcp-dns on a smeserver
you missed to enable my repository

see http://wiki.contribs.org/Stephdl

**Comment by CmdLnInt** [comment]
Thanks but now I get this

```
[root@server ~]# yum --enablerepo=stephdl install smeserver-dhcp-dns
Loaded plugins: fastestmirror, protect-packages, smeserver
Loading mirror speeds from cached hostfile
 * base: mirror.bitco.co.za
 * smeaddons: mirror.enpol-ict.net
 * smeextras: mirror.enpol-ict.net
 * smeos: mirror.enpol-ict.net
 * smeupdates: mirror.enpol-ict.net
 * updates: mirror.bitco.co.za
Excluding Packages from CentOS - os
Finished
Excluding Packages from CentOS - updates
Finished
Setting up Install Process
No package smeserver-dhcp-dns available.
Nothing to do
```

**Comment by stephdl** [comment]
my bad I have recently imported it to smecontribs, please follow up http://wiki.contribs.org/Dhcp-dns#Installation

**Comment by CmdLnInt** [comment]
Ok all good now.

**Comment by stephdl** [comment]
good :)
